# Generated by Django 4.2.6 on 2023-10-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='portfolio/images/default.png', upload_to='media/portfolio/images/'),
        ),
    ]
