# Generated by Django 4.2.6 on 2023-10-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_projects_options_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='portfolio/images/default.png', upload_to='portfolio/images/'),
        ),
    ]
